### PR TITLE
code-quality/fix-component-export-inconsistency

### PR DESCRIPTION
**Pull request by hawkticehurst**
**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [ ] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
- [x] Provide context of changes.
- [ ] Provide relevant tests for your feature or bug fix.
- [ ] Provide or update documentation for any feature added by your pull request.

**Summary Of Changes**
PR resolves an inconsistency with how components were being exported (i.e. named vs default exports).

Based on a [conversation](https://councildataproject.slack.com/archives/CMPTLMY9L/p1610397136024200) in the team Slack, the decision was to follow a guideline that all components must use default exports. 

Each directory containing a component must also have an `index.ts` file which then exports the components as a named export (i.e. `export {default as ComponentName} from './ComponentName';`) so that eventually all components can be exported under one namespace in the NPM package associated with this repo.

### CODE REVIEW

**Review by tohuynh — CHANGES_REQUESTED** [review]
It looks good. Thanks for doing this. There's a minor difference from what we talked about.

I think we decided on the structure:
```
ComponentName/ComponentName.tsx
ComponentName/ComponentName.stories.mdx
ComponentName/index.ts
```
In which  Base and MeetingCard need their own dir.
(The Base component doesn't need a stories file)

**Comment by hawkticehurst** [comment]
Ooh, thanks for the reminder! Coming right up.

**Comment by tohuynh** [comment]
> Ooh, thanks for the reminder! Coming right up.

Just heads up, the file path of MeetingCard src/index.ts would change as well

**Comment by hawkticehurst** [comment]
Yep, I caught that one!

**Review by tohuynh — APPROVED** [review]
Awesome, thanks for resolving the change request.

**Pull request merged**
