### PR TITLE
feature/localize-date-to-instance-time-zone

### PR DESCRIPTION
**Pull request by tohuynh**
### Link to Relevant Issue

This pull request resolves
part of #112 

### Description of Changes

_Include a description of the proposed changes._
Remove `moment` lib to reduce CDP-frontend lib size and decrease the app load time.

I added an IANA `timeZone` to the app config context and use it throughout the app to display dates. Now all dates are displayed according to the instance's time zone. For example, anyone around the world viewing Seattle's date will always see 2 PM Seattle time (if the event started at 2 PM Seattle time). Previously, it was displayed according to the user's time zone. This is done by adding a time zone to `date.toLocaleDateString` or `date.toLocaleString`

Even selecting a date in the filter component means selecting a date in the instance's time zone. For example, selecting 1/1/2022 in the Seattle instance means selecting 1/1/2022, 12 AM Seattle time. The conversion is done with `getTimeZoneDate`.

### Link to Forked Storybook Site

_If component changes (especially visual changes) are contained in this PR, we ask that you provide a link to a publicly viewable version of the Storybook docs site, so PR reviewers can see your changes without having to install and view your code locally._

_Please see `CONTRIBUTING.md` for directions on how this can be done._
https://tohuynh.github.io/cdp-frontend/#/events/756436a9130b

### CODE REVIEW

**Review by JacksonMaxfield — COMMENTED** [review]
This all looks good for me. I am not going to approve and merge until https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/issues/83 is resolved.

Totally agree with both changes proposed here and in and cookiecutter just a matter of order-of-operations.

**Comment by tohuynh** [comment]
> This all looks good for me. I am not going to approve and merge until [CouncilDataProject/cookiecutter-cdp-deployment#83](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/issues/83) is resolved.
> 
> Totally agree with both changes proposed here and in and cookiecutter just a matter of order-of-operations.

Sounds good

**Review by BrianL3 — APPROVED** [review]
We should be sure to add some documentation to ensure people know how to properly format the timezone info that goes into the cookie cutter.

**Comment by JacksonMaxfield** [comment]
@tohuynh I am going to ship a new release of stuff today. When possible can you fix the merge conflict and I will get it into the next release -- next week or something

**Comment by tohuynh** [comment]
> @tohuynh I am going to ship a new release of stuff today. When possible can you fix the merge conflict and I will get it into the next release -- next week or something

Ship new release, but won't propagate these changes to all the instances, right?

**Comment by JacksonMaxfield** [comment]
Yep sorry for this taking so long. Completely my fault.

**Comment by tohuynh** [comment]
> Yep sorry for this taking so long. Completely my fault.

No worries!

**Pull request merged**
